apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: app
  labels:
    app: weather-app
spec:
  replicas: {{ .Values.replicas.num }}
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.image.containerPort }}