apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  namespace: app
  labels:
    app: weather-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.image.containerPort }}
  selector:
    app: weather-app