pipeline 
{
	agent 
	{
		kubernetes
		{
yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
    - cat
    tty: true
  - name: helm
    image: alpine/helm:3.12.3
    command:
    - cat
    tty: true

''' // Agent pod with two containers: Kaniko for build + publish, Helm for deploy. (DnD)
		}
	}

	environment
	{
		AWS_REGION = 'eu-central-1'
		ECR_REPO = "122610493328.dkr.ecr.${AWS_REGION}.amazonaws.com/weatherapp"
	}

	stages
	{
		stage('Build and Publish')
		{
			steps
			{
				container('kaniko')
				{
					sh """
            			/kaniko/executor --dockerfile=./Question1/WeatherApp/Dockerfile \
                        --context=/workspace \
                        --destination=${ECR_REPO}:latest
            		"""
				}
			}
		}

		stage('Deploy')
		{
			steps
			{
				container('helm')
				{
					sh "helm upgrade --install weather-app ./Question1/HelmCharts/WeatherAppChart --namespace app"
				}
			}
		}
	}
}