apiVersion: v1
kind: Pod
spec:
  containers:
  - name: aws
    image: amazon/aws-cli:latest
    securityContext:
      runAsUser: 0
      privileged: true
    command:
    - cat
    tty: true
    volumeMounts:
    - name: shared-credentials
      mountPath: /root/.docker
  - name: buildkit
    image: moby/buildkit:master
    securityContext:
      runAsUser: 0
      privileged: true
    tty: true
    volumeMounts:
    - name: shared-credentials
      mountPath: /root/.docker
  - name: helm
    image: alpine/helm:3.12.3
    command:
    - cat
    tty: true
  volumes:
  - name: shared-credentials
    emptyDir: {}
